apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app   # Root app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Juangmz7/Kubernetes-cloud-infrastructure.git'
    targetRevision: HEAD
    path: infra/argocd-apps  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd        # Installed at argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true