apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Juangmz7/Kubernetes-cloud-infrastructure.git' 
    targetRevision: HEAD
    path: apps/redis-tcp
  destination:
    server: https://kubernetes.default.svc
    namespace: final-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true